### ISSUE TITLE
Make reverse DNS schema consistent

### ISSUE THREAD

**Issue by TheEvilSkeleton** [Lea-fish/Leafish#124]
I noticed that the reverse DNS schemas we are using are inconsistent at the moment:

Linux:
https://github.com/Lea-fish/Leafish/blob/68337e648f53982efd10f5ce882bc82010934a47/packaging/leafish.metainfo.xml#L3

Cargo:
https://github.com/Lea-fish/Leafish/blob/08a98f0135255b40e37037fd965afb0874d6bbdb/Cargo.toml#L13

We should either choose `io.github.*` or `com.github.*`.

And just an FYI, since the new org is Lea-fish, it's best to update the metadata files.

I can be assigned if needed.

**Comment by PureTryOut** [comment]
Note that you don't have to make issues for every simple thing you can do, just do it :wink: 

And yeah it has to be updated to use lea-fish rather than terrarier2111.

**Comment by TheEvilSkeleton** [comment]
I just wanted to have a discussion because we have two possible options. I personally prefer `com.github`, but if you prefer `io.github`, then I'll use that one.

**Comment by PureTryOut** [comment]
Ah. I'd use `com.github` as that is basically the site url but reversed.
