### ISSUE TITLE
Too long chat messages overlap each other

### ISSUE THREAD

**Issue by PureTryOut** [Lea-fish/Leafish#143]
As indicated in #138. Basically when a message is 2 or more lines, the next message overlaps it rather than making space for it.

**Comment by terrarier2111** [comment]
Fixed by https://github.com/Lea-fish/Leafish/commit/5986fc67bc90870b6bdc01d819dc7e63b33618b7

**Comment by PureTryOut** [comment]
@terrarier2111 for next time, if you put "Fixes #<issue number>" in either the commit message or the PR description, then Github will close it automatically.
