### ISSUE TITLE
Unable to launch game due to mojang account issue

### ISSUE THREAD

**Issue by 0xEquinox** [Lea-fish/Leafish#152]
Currently each account will only have one single profile, multiple profiles per account are however planned in the future. If a user attempts to log into a valid Mojang account with no attached Minecraft license, the authentication will be successful, but the response will not contain a selectedProfile field, and the availableProfiles array will be empty.
Some instances in the wild have been observed of Mojang returning a flat null for failed refresh attempts against legacy accounts. It's not clear what the actual error tied to the null response is and it is extremely rare, but implementations should be wary of null output from the response.

My account was created in 2013 or 2014, currently still a Mojang account that has yet to be migrated. I do not change my username often I think it has been changed a total of 2 times. My current user name is: EquinoxOV

**Comment by terrarier2111** [comment]
This is the link to the profile's namemc: https://de.namemc.com/profile/EquinoxOV.1
