### ISSUE TITLE
Login page, takes cursor, can't write in the input fields

### ISSUE THREAD

**Issue by kepet19** [Lea-fish/Leafish#158]
Login page, takes cursor, can't write in the input fields.
this happens on main branch latest commit: 6f8783b

**Comment by terrarier2111** [comment]
Could you make a video demonstrating this issue?

**Comment by kepet19** [comment]
As soon as I start writing the cursor Disappear.
When I then unfocused the application and go back to the application cursor disappears  right away.

https://user-images.githubusercontent.com/55736468/133076983-14ed7781-6a6c-4dff-a1c5-8f619d5526c7.mp4

**Comment by terrarier2111** [comment]
Could you try it again, i think i fixed it in: https://github.com/Lea-fish/Leafish/commit/0587d9357dcc6a15df4cde96e664d118cb877458

**Comment by PureTryOut** [comment]
Yup that fixed it, thanks!
