### ISSUE TITLE
In the folder /resources there are 2 icons that are the old steven logo.

### ISSUE THREAD

**Issue by kepet19** [Lea-fish/Leafish#185]
In the folder root/resources there are 2 icons that are the old steven logo.
Maybe change it to the new SVG icons.  `Leafish/resources/assets/leafish/logo/leafish-logo.svg`

These are the offenders. 
`Leafish/resources/icon128x128.png`
`Leafish/resources/icon32x32.png`

I believe these icons is getting  used on Mac'os version.

**Comment by skillman623** [comment]
Fixed in #302.
