### ISSUE TITLE
Trying to join a server without ip and name crashes the client

### ISSUE THREAD

**Issue by Luro02** [Lea-fish/Leafish#196]
To reproduce:
1. Click Add Button in Server List
2. Click Done without entering anything in the fields
3. A new empty server will be added to the list
4. Clicking on it will result in a crash

**Comment by terrarier2111** [comment]
we should prevent such servers being added altogether

**Comment by kepet19** [comment]
https://user-images.githubusercontent.com/55736468/135323296-3891232b-922f-42c0-9da0-e41cec12f6cb.mp4
I can't seem to reproduce.

**Comment by terrarier2111** [comment]
> out.mp4
> 
> I can't seem to reproduce.
> 
> Latest main branch - [9176d74](https://github.com/Lea-fish/Leafish/commit/9176d74d496b641e6da91bc81cec44292b95d951)

I think we should still disallow empty address fields for serverlist entries

**Comment by Luro02** [comment]
I am on Windows, maybe this helps?

**Comment by terrarier2111** [comment]
This should be fixed now
