### ISSUE TITLE
Client crashes when connecting to 1.16.5 Server

### ISSUE THREAD

**Issue by schitcrafter** [Lea-fish/Leafish#215]
I tried running a local Spigot 1.16.5 server, and connecting to it with Leafish (on commit fcdfa40), but about half a second after I connected, the client crashes with the following console output:

[leafish_crash.txt](https://github.com/Lea-fish/Leafish/files/7620540/leafish_crash.txt)

I did get a couple of frames rendered before it crashed, but I could only see my own body and some boxes without textures on them.

**Comment by schitcrafter** [comment]
I investigated a bit more, and this is happening because in /protocol/src/protocol/mod.rs after line 879, this code is present:

```rust
/// `VarInt` have a variable size (between 1 and 5 bytes) when encoded based
/// on the size of the number
#[derive(Clone, Copy)]
pub struct VarInt(pub i32);

impl Lengthable for VarInt {
    fn into_len(self) -> usize {
        self.0 as usize
    }

    fn from_len(u: usize) -> VarInt {
        VarInt(u as i32)
    }
}

impl Serializable for VarInt {
    /// Decodes a `VarInt` from the Reader
    fn read_from<R: io::Read>(buf: &mut R) -> Result<VarInt, Error> {
        const PART: u32 = 0x7F;
        let mut size = 0;
        let mut val = 0u32;
        loop {
            let b = buf.read_u8()? as u32;
            val |= (b & PART) << (size * 7); /// <- failed here, specifically at the bit-shift
            size += 1;
            if size > 5 {
                return Err(Error::Err("VarInt too big".to_owned()));
            }
            if (b & 0x80) == 0 {
                break;
            }
        }

        Ok(VarInt(val as i32))
    }
    /// snip
}
```
As you can see, `VarInt` is supposed to hold 1-5 bytes, but only holds 4 bytes ( `i32`). Because of this, in the `read_from` function, `PART` `val`, `b` as well as the cast `val as i32` use 32 bit types. Because of this, when `buf` holds more than 4 bytes of data, the loop fails in the 5th time it's run (at size == 5), because then you'd be bit-shifting a 32-bit value by 35 bits, causing the error you see above. This happens at the line 
```rust
val |= (b & PART) << (size * 7);
```

I can see two solutions:
 - Making `VarInt` use i64, which would require changing a lot of code
 - Say that `VarInt` can only hold up to 4 bytes, and change `read_from` accordingly (fail at `size > 4`, and fail before executing the line above)

**Comment by schitcrafter** [comment]
I tried the second solution but I'm getting a SIGSEGV (Address boundary error) now, so this might not be a good solution

**Comment by schitcrafter** [comment]
Ok so thanks to a very helpful guy in the Rust Discord server, I managed to get a coredump and backtrace:
```
#0  0x00007ffa353effc9 in  () at /usr/lib/libGLdispatch.so.0
#1  0x000055afc94e6390 in glow::gl46::call_atomic_ptr_2arg<(), i32, *const u32> (name=..., ptr=<optimized out>, a=<optimized out>, b=<optimized out>)
at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/glow-0.10.0/src/gl46.rs:4313
#2  glow::gl46::struct_commands::GlFns::DeleteVertexArrays (self=<optimized out>, n=1, arrays=0x7ffa239f8e54) at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/glow-0.10.0/src/gl46.rs:10909
#3  0x000055afc94ee104 in glow::native::{impl#2}::delete_vertex_array (self=0x1, vertex_array=9) at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/glow-0.10.0/src/native.rs:389
#4  0x000055afc9060034 in leafish::gl::{impl#10}::drop (self=0x7ffa239f8f18) at src/gl/mod.rs:678
#5  0x000055afc9044176 in core::ptr::drop_in_place<leafish::gl::VertexArray> () at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ptr/mod.rs:188
#6  0x000055afc904543e in core::ptr::drop_in_place<leafish::render::model::Model> () at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ptr/mod.rs:188
#7  0x000055afc9158b4c in core::ptr::drop_in_place<core::option::Option<leafish::render::model::Model>> () at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ptr/mod.rs:188
#8  0x000055afc915a992 in leafish::render::model::Manager::remove_model (self=<optimized out>, key=0x55afcd249040) at src/render/model.rs:213
#9  0x000055afc90600d2 in leafish::render::model::{impl#3}::drop (self=0x55afcd249040) at src/render/model.rs:62
#10 0x000055afc904689c in core::ptr::drop_in_place<leafish::render::model::ModelHandle> () at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ptr/mod.rs:188
#11 0x000055afc904d95d in core::ptr::drop_in_place<core::option::Option<leafish::render::model::ModelHandle>> () at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ptr/mod.rs:188
#12 0x000055afc9046bac in core::ptr::drop_in_place<leafish::entity::zombie::ZombieModel> () at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ptr/mod.rs:188
#13 0x000055afc90ae2d6 in core::ptr::mut_ptr::{impl#0}::drop_in_place<leafish::entity::zombie::ZombieModel> (self=0x1) at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ptr/mut_ptr.rs:996
#14 bevy_ecs::component::ComponentDescriptor::drop_ptr<leafish::entity::zombie::ZombieModel> (x=0x1) at /home/jonas/.cargo/git/checkouts/bevy-dbab41c994e5767b/a58b493/crates/bevy_ecs/src/component.rs:183
#15 0x000055afc9c31ef5 in bevy_ecs::storage::blob_vec::BlobVec::swap_remove_and_drop_unchecked (self=0x55afcd2a47b0, index=1) at /home/jonas/.cargo/git/checkouts/bevy-dbab41c994e5767b/a58b493/crates/bevy_ecs/src/storage/blob_vec.rs:163
#16 0x000055afc9c32123 in bevy_ecs::storage::table::Column::swap_remove_unchecked (self=0x55afcd2a47a8, row=1) at /home/jonas/.cargo/git/checkouts/bevy-dbab41c994e5767b/a58b493/crates/bevy_ecs/src/storage/table.rs:108
#17 0x000055afc9c3239b in bevy_ecs::storage::table::Table::swap_remove_unchecked (self=0x7ff9f8248aa0, row=1) at /home/jonas/.cargo/git/checkouts/bevy-dbab41c994e5767b/a58b493/crates/bevy_ecs/src/storage/table.rs:234
#18 0x000055afc9c0402a in bevy_ecs::world::entity_ref::EntityMut::despawn (self=...) at /home/jonas/.cargo/git/checkouts/bevy-dbab41c994e5767b/a58b493/crates/bevy_ecs/src/world/entity_ref.rs:433
#19 0x000055afc90824dd in bevy_ecs::world::{impl#1}::despawn::{closure#0} (e=...) at /home/jonas/.cargo/git/checkouts/bevy-dbab41c994e5767b/a58b493/crates/bevy_ecs/src/world/mod.rs:462
#20 0x000055afc907e522 in core::option::Option<bevy_ecs::world::entity_ref::EntityMut>::map<bevy_ecs::world::entity_ref::EntityMut, bool, bevy_ecs::world::{impl#1}::despawn::{closure#0}> (self=..., f=...)
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/option.rs:836
#21 0x000055afc90824af in bevy_ecs::world::World::despawn (self=<optimized out>, entity=...) at /home/jonas/.cargo/git/checkouts/bevy-dbab41c994e5767b/a58b493/crates/bevy_ecs/src/world/mod.rs:460
#22 0x000055afc908ecbb in leafish::server::Server::on_entity_destroy (self=<optimized out>, entity_destroy=...) at src/server/mod.rs:1896
#23 0x000055afc910edaa in leafish::server::{impl#1}::spawn_reader::{closure#0} () at src/server/mod.rs:501
#24 0x000055afc9106d97 in std::sys_common::backtrace::__rust_begin_short_backtrace<leafish::server::{impl#1}::spawn_reader::{closure#0}, ()> (f=...)
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:125
#25 0x000055afc91ed347 in std::thread::{impl#0}::spawn_unchecked::{closure#0}::{closure#0}<leafish::server::{impl#1}::spawn_reader::{closure#0}, ()> () at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/mod.rs:481
#26 0x000055afc91ece27 in core::panic::unwind_safe::{impl#23}::call_once<(), std::thread::{impl#0}::spawn_unchecked::{closure#0}::{closure#0}> (self=..., _args=())
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panic/unwind_safe.rs:271
#27 0x000055afc9202473 in std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked::{closure#0}::{closure#0}>, ()> (data=<optimized out>)
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403
#28 0x000055afc9202db4 in __rust_try.llvm.8406549336642644524 ()
#29 0x000055afc9202185 in std::panicking::try<(), core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked::{closure#0}::{closure#0}>> (f=...)
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367
#30 0x000055afc9195ce7 in std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked::{closure#0}::{closure#0}>, ()> (f=...)
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129
#31 0x000055afc91933bf in std::thread::{impl#0}::spawn_unchecked::{closure#0}<leafish::server::{impl#1}::spawn_reader::{closure#0}, ()> () at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/mod.rs:480
#32 0x000055afc91944b6 in core::ops::function::FnOnce::call_once<std::thread::{impl#0}::spawn_unchecked::{closure#0}, ()> () at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227
#33 0x000055afc9ca4883 in alloc::boxed::{impl#44}::call_once<(), dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global> () at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/boxed.rs:1636
#34 alloc::boxed::{impl#44}::call_once<(), alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>, alloc::alloc::Global> ()
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/boxed.rs:1636
#35 std::sys::unix::thread::{impl#2}::new::thread_start () at library/std/src/sys/unix/thread.rs:106
#36 0x00007ffa39bd2259 in start_thread () at /usr/lib/libpthread.so.0
#37 0x00007ffa399b75e3 in clone () at /usr/lib/libc.so.6
```
This suggests that the issue has something to do with glow/OpenGL, which is very odd considering this is in networking code

**Comment by terrarier2111** [comment]
> Ok so thanks to a very helpful guy in the Rust Discord server, I managed to get a coredump and backtrace:
> 
> ```
> #0  0x00007ffa353effc9 in  () at /usr/lib/libGLdispatch.so.0
> #1  0x000055afc94e6390 in glow::gl46::call_atomic_ptr_2arg<(), i32, *const u32> (name=..., ptr=<optimized out>, a=<optimized out>, b=<optimized out>)
> at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/glow-0.10.0/src/gl46.rs:4313
> #2  glow::gl46::struct_commands::GlFns::DeleteVertexArrays (self=<optimized out>, n=1, arrays=0x7ffa239f8e54) at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/glow-0.10.0/src/gl46.rs:10909
> #3  0x000055afc94ee104 in glow::native::{impl#2}::delete_vertex_array (self=0x1, vertex_array=9) at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/glow-0.10.0/src/native.rs:389
> #4  0x000055afc9060034 in leafish::gl::{impl#10}::drop (self=0x7ffa239f8f18) at src/gl/mod.rs:678
> #5  0x000055afc9044176 in core::ptr::drop_in_place<leafish::gl::VertexArray> () at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ptr/mod.rs:188
> #6  0x000055afc904543e in core::ptr::drop_in_place<leafish::render::model::Model> () at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ptr/mod.rs:188
> #7  0x000055afc9158b4c in core::ptr::drop_in_place<core::option::Option<leafish::render::model::Model>> () at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ptr/mod.rs:188
> #8  0x000055afc915a992 in leafish::render::model::Manager::remove_model (self=<optimized out>, key=0x55afcd249040) at src/render/model.rs:213
> #9  0x000055afc90600d2 in leafish::render::model::{impl#3}::drop (self=0x55afcd249040) at src/render/model.rs:62
> #10 0x000055afc904689c in core::ptr::drop_in_place<leafish::render::model::ModelHandle> () at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ptr/mod.rs:188
> #11 0x000055afc904d95d in core::ptr::drop_in_place<core::option::Option<leafish::render::model::ModelHandle>> () at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ptr/mod.rs:188
> #12 0x000055afc9046bac in core::ptr::drop_in_place<leafish::entity::zombie::ZombieModel> () at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ptr/mod.rs:188
> #13 0x000055afc90ae2d6 in core::ptr::mut_ptr::{impl#0}::drop_in_place<leafish::entity::zombie::ZombieModel> (self=0x1) at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ptr/mut_ptr.rs:996
> #14 bevy_ecs::component::ComponentDescriptor::drop_ptr<leafish::entity::zombie::ZombieModel> (x=0x1) at /home/jonas/.cargo/git/checkouts/bevy-dbab41c994e5767b/a58b493/crates/bevy_ecs/src/component.rs:183
> #15 0x000055afc9c31ef5 in bevy_ecs::storage::blob_vec::BlobVec::swap_remove_and_drop_unchecked (self=0x55afcd2a47b0, index=1) at /home/jonas/.cargo/git/checkouts/bevy-dbab41c994e5767b/a58b493/crates/bevy_ecs/src/storage/blob_vec.rs:163
> #16 0x000055afc9c32123 in bevy_ecs::storage::table::Column::swap_remove_unchecked (self=0x55afcd2a47a8, row=1) at /home/jonas/.cargo/git/checkouts/bevy-dbab41c994e5767b/a58b493/crates/bevy_ecs/src/storage/table.rs:108
> #17 0x000055afc9c3239b in bevy_ecs::storage::table::Table::swap_remove_unchecked (self=0x7ff9f8248aa0, row=1) at /home/jonas/.cargo/git/checkouts/bevy-dbab41c994e5767b/a58b493/crates/bevy_ecs/src/storage/table.rs:234
> #18 0x000055afc9c0402a in bevy_ecs::world::entity_ref::EntityMut::despawn (self=...) at /home/jonas/.cargo/git/checkouts/bevy-dbab41c994e5767b/a58b493/crates/bevy_ecs/src/world/entity_ref.rs:433
> #19 0x000055afc90824dd in bevy_ecs::world::{impl#1}::despawn::{closure#0} (e=...) at /home/jonas/.cargo/git/checkouts/bevy-dbab41c994e5767b/a58b493/crates/bevy_ecs/src/world/mod.rs:462
> #20 0x000055afc907e522 in core::option::Option<bevy_ecs::world::entity_ref::EntityMut>::map<bevy_ecs::world::entity_ref::EntityMut, bool, bevy_ecs::world::{impl#1}::despawn::{closure#0}> (self=..., f=...)
> at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/option.rs:836
> #21 0x000055afc90824af in bevy_ecs::world::World::despawn (self=<optimized out>, entity=...) at /home/jonas/.cargo/git/checkouts/bevy-dbab41c994e5767b/a58b493/crates/bevy_ecs/src/world/mod.rs:460
> #22 0x000055afc908ecbb in leafish::server::Server::on_entity_destroy (self=<optimized out>, entity_destroy=...) at src/server/mod.rs:1896
> #23 0x000055afc910edaa in leafish::server::{impl#1}::spawn_reader::{closure#0} () at src/server/mod.rs:501
> #24 0x000055afc9106d97 in std::sys_common::backtrace::__rust_begin_short_backtrace<leafish::server::{impl#1}::spawn_reader::{closure#0}, ()> (f=...)
> at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:125
> #25 0x000055afc91ed347 in std::thread::{impl#0}::spawn_unchecked::{closure#0}::{closure#0}<leafish::server::{impl#1}::spawn_reader::{closure#0}, ()> () at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/mod.rs:481
> #26 0x000055afc91ece27 in core::panic::unwind_safe::{impl#23}::call_once<(), std::thread::{impl#0}::spawn_unchecked::{closure#0}::{closure#0}> (self=..., _args=())
> at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panic/unwind_safe.rs:271
> #27 0x000055afc9202473 in std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked::{closure#0}::{closure#0}>, ()> (data=<optimized out>)
> at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403
> #28 0x000055afc9202db4 in __rust_try.llvm.8406549336642644524 ()
> #29 0x000055afc9202185 in std::panicking::try<(), core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked::{closure#0}::{closure#0}>> (f=...)
> at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367
> #30 0x000055afc9195ce7 in std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked::{closure#0}::{closure#0}>, ()> (f=...)
> at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129
> #31 0x000055afc91933bf in std::thread::{impl#0}::spawn_unchecked::{closure#0}<leafish::server::{impl#1}::spawn_reader::{closure#0}, ()> () at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/mod.rs:480
> #32 0x000055afc91944b6 in core::ops::function::FnOnce::call_once<std::thread::{impl#0}::spawn_unchecked::{closure#0}, ()> () at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227
> #33 0x000055afc9ca4883 in alloc::boxed::{impl#44}::call_once<(), dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global> () at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/boxed.rs:1636
> #34 alloc::boxed::{impl#44}::call_once<(), alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>, alloc::alloc::Global> ()
> at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/boxed.rs:1636
> #35 std::sys::unix::thread::{impl#2}::new::thread_start () at library/std/src/sys/unix/thread.rs:106
> #36 0x00007ffa39bd2259 in start_thread () at /usr/lib/libpthread.so.0
> #37 0x00007ffa399b75e3 in clone () at /usr/lib/libc.so.6
> ```
> 
> This suggests that the issue has something to do with glow/OpenGL, which is very odd considering this is in networking code What's probably happening is, a entity gets destroyed (because of the call to leafish::server::Server::on_entity_destroy), bevy_ecs takes that entity out of the system, tries to destroy a Vertex Array, and then fails at that.

Looks like its a bug in your OpenGL backend

**Comment by schitcrafter** [comment]
Don't think it's a thing in my OpenGL backend tbh (as someone else could also reproduce it), from my debugging it seems like the pointer to the function that destroys Vertex Arrays is pointing to an invalid address (inside the glow context) - but as this is gonna switch to wgpu-mc anyway I'm closing
