### ISSUE TITLE
Cannot play leafish

### ISSUE THREAD

**Issue by remaster2011** [Lea-fish/Leafish#243]
I have a Microsoft account and whenever i try to log into leafish it gives me an error. Please help. Thanks

**Comment by skillman623** [comment]
> I have a Microsoft account and whenever i try to log into leafish it gives me an error. Please help. Thanks

Hello, we are aware if this issue and are resolving it under #188.
This will be addressed soon as it is something I am actively working to resolve.

**Comment by Evilhotdog** [comment]
> Thanks for the reply. I am looking forward to play this! I cannot believe I can play real minecraft servers with this. I was wondering, is there some way to just play localhost or something while this is being fixed?

I think you would have to enable offline mode in your localhost server's config, meaning it won't verify accounts that connect to it. That said, I remember #222 saying that there was a bug with localhost? Though this might have still been talking about mojang accounts. I guess you'd have to test it yourself.

**Comment by terrarier2111** [comment]
If anyone want to pick this up, there is a simpler alternative to fix this which is to embedd leafish into a jar which just starts leafish and passes it the relevant information from the minecraft launcher, so we can just use microsoft's infrastructure to not have to deal this ourselves

**Comment by skillman623** [comment]
> If anyone want to pick this up, there is a simpler alternative to fix this which is to embedd leafish into a jar which just starts leafish and passes it the relevant information from the minecraft launcher, so we can just use microsoft's infrastructure to not have to deal this ourselves

I'm in favor of this solution but will also be implementing the Microsoft auth when I get time for users who want a fully open source solution.

**Comment by remaster2011** [comment]
> > If anyone want to pick this up, there is a simpler alternative to fix this which is to embedd leafish into a jar which just starts leafish and passes it the relevant information from the minecraft launcher, so we can just use microsoft's infrastructure to not have to deal this ourselves
> 
> How do I do that?

Dont want to be pushy but its been a week now and there hasnt been any replies and i still want to play leafish. I have attempted to embed to a jar but I need to know how

**Comment by terrarier2111** [comment]
> > > If anyone want to pick this up, there is a simpler alternative to fix this which is to embedd leafish into a jar which just starts leafish and passes it the relevant information from the minecraft launcher, so we can just use microsoft's infrastructure to not have to deal this ourselves
> > 
> > 
> > How do I do that?
> 
> Dont want to be pushy but its been a week now and there hasnt been any replies and i still want to play leafish. I have attempted to embed to a jar but I need to know how

I don't think that i am able to provide more information on this than i already did. But what you basically have to do is:
1: Create a jar which takes the parameters a normal minecraft client would
2: Create a new startup function inside Leafish which is no_mangle and C-ABI compatible
3: Remove/disable (almost) the entire account system which Leafish has and work with the info provided via the startup parameters instead
3: Use JNI to call that startup function from the jar
4: Compile Leafish as a non-application (the appropriate crate type would probably be lib or dylib)
5: Embed the Leafish lib into the jar
6: Compile the jar
7: Provide the necessary information to the mc launcher (via some metadata files and stuff) and put the compiled jar in the appropriate place so the launcher detects the jar as a minecraft version

**Comment by remaster2011** [comment]
> > > > If anyone want to pick this up, there is a simpler alternative to fix this which is to embedd leafish into a jar which just starts leafish and passes it the relevant information from the minecraft launcher, so we can just use microsoft's infrastructure to not have to deal this ourselves
> > > 
> > > 
> > > How do I do that?
> > 
> > 
> > Dont want to be pushy but its been a week now and there hasnt been any replies and i still want to play leafish. I have attempted to embed to a jar but I need to know how
> 
> I don't think that i am able to provide much more information on this than i already did. But what you basically have to do is: 1: Create a jar which takes the parameters a normal minecraft client would 2: Create a new startup function inside Leafish which is no_mangle and C-ABI compatible 3: Remove/disable (almost) the entire account system which Leafish has and work with the info provided via the startup parameters instead 4: Use JNI to call that startup function from the jar 5: Compile Leafish as a non-application (the appropriate crate type would probably be lib or dylib) 6: Embed the Leafish lib into the jar 7: Compile the jar 8: Provide the necessary information to the mc launcher (via some metadata files and stuff) and put the compiled jar in the appropriate place so the launcher detects the jar as a minecraft version

Wow... thats a lot of stuff todo. I could probably do this if I really wanted to but I am not a rust programmer (want to be though, im scared of the syntax though). Is it possible if you can just send me the jar you have?

**Comment by terrarier2111** [comment]
> 

Fair enough but that would still require one to remove/rework Leafish's account/login system almost entirely

**Comment by terrarier2111** [comment]
@remaster2011
I don't have a working jar or else i'd already have implemented this method into a launcher/installer or such.

**Comment by gIsForGravity** [comment]
> > > > If anyone want to pick this up, there is a simpler alternative to fix this which is to embedd leafish into a jar which just starts leafish and passes it the relevant information from the minecraft launcher, so we can just use microsoft's infrastructure to not have to deal this ourselves
> 
> > > 
> 
> > > 
> 
> > > How do I do that?
> 
> > 
> 
> > Dont want to be pushy but its been a week now and there hasnt been any replies and i still want to play leafish. I have attempted to embed to a jar but I need to know how
> 
> 
> 
> I don't think that i am able to provide much more information on this than i already did. But what you basically have to do is:
> 
> 1: Create a jar which takes the parameters a normal minecraft client would
> 
> 2: Create a new startup function inside Leafish which is no_mangle and C-ABI compatible
> 
> 3: Remove/disable (almost) the entire account system which Leafish has and work with the info provided via the startup parameters instead
> 
> 4: Use JNI to call that startup function from the jar
> 
> 5: Compile Leafish as a non-application (the appropriate crate type would probably be lib or dylib)
> 
> 6: Embed the Leafish lib into the jar
> 
> 7: Compile the jar
> 
> 8: Provide the necessary information to the mc launcher (via some metadata files and stuff) and put the compiled jar in the appropriate place so the launcher detects the jar as a minecraft version

I feel like you're over complicating this. Instead of calling an extern c function in Leafish, why don't we just make a jar that just starts the leafish executable in a new process?

**Comment by skillman623** [comment]
I now have an Azure API server for this project.
Now the client side work needs to be done.

**Comment by terrarier2111** [comment]
> I have a Microsoft account and whenever i try to log into leafish it gives me an error. Please help. Thanks

This should be fixed by the new installer
