### ISSUE TITLE
Standardize contribution terms.

### ISSUE THREAD

**Issue by skillman623** [Lea-fish/Leafish#245]
We really should make a clause that licenses all code under one license.
By default if someone doesn't put in a license for their code, it's assumed to be all rights reserved.

**Comment by terrarier2111** [comment]
Unfortunately i have no experience with such legal stuff, so feel free to add licensing thingies

**Comment by artswithastriya** [comment]
> Unfortunately i have no experience with such legal stuff, so feel free to add licensing thingies

We can simply copy the clauses commonly found on other standard-licensed Rust projects.
https://github.com/bevyengine/bevy#license

https://github.com/bevyengine/bevy#your-contributions

**Comment by artswithastriya** [comment]
> We really should make a clause that licenses all code under one license. By default if someone doesn't put in a license for their code, it's assumed to be all rights reserved.

I'm not a professional lawyer, but many bigger projects don't put copyright notices to their source files too actually, including Bevy and the Rust compiler. 

I think what matters more is whether contributors are aware that this project is licensed MIT/Apache2 but this is generally something that a non-lawyer like me can't answer.

**Comment by terrarier2111** [comment]
> We really should make a clause that licenses all code under one license. By default if someone doesn't put in a license for their code, it's assumed to be all rights reserved.

Its not really all rights reserved as the license of the repository automatically applies to all the contributions to it and as such the contributors while holding onto the copyright give us the permission to use, distribute and modify the code

**Comment by terrarier2111** [comment]
At least from my understanding of the licenses

**Comment by artswithastriya** [comment]
> At least from my understanding of the licenses

I don't think your understanding is wrong.

I realize this issue is a bit vaguely worded though. There isn't any clear actions suggested or anything like that. But if you are someone concerned about potential issues, I do think it's better to take more steps to clear the copyright status. In things like copyright agreements or contracts in general, even the smallest wrong or vague details can make things a disaster.

More copyright-minding maintainers, like those that monetize their open source project, usually would make sure everything about the copyright is clear by having CLAs, DCOs, or license headers.

**Comment by terrarier2111** [comment]
> > At least from my understanding of the licenses
> 
> I don't think your understanding is wrong, but I believe the better understanding would be that "contributors are consciously aware and agree that submitting code to this project means licensing the code under the project's license". Someone might argue in court that if they do not consciously aware and agree about it, things might be null.
> 
> I realize this issue in particular is a bit vaguely worded though. There isn't any clear actions suggested or anything like that.
> 
> But if you are someone who is concerned about potential issues, I do think it's better to take more steps to clear the copyright status. In things like copyright agreements or contracts in general, even the smallest wrong or vague details can make things a disaster.
> 
> More copyright-minding maintainers, like those that monetize their open source project, usually would make sure everything about the copyright is clear by having CLAs, DCOs, or license headers.
> 
> But generally as I write earlier taking these "extra" measures are not everywhere in the open source world. The convention in the Rust world is to include a copyright disclaimer in the README.

Thank you for your insight, i added a license disclaimer in https://github.com/Lea-fish/Leafish/commit/2537087160fd88a18f4a2d7e6a448167243c1f5c do you think this is sufficient?

**Comment by artswithastriya** [comment]
> > > At least from my understanding of the licenses
> > 
> > 
> > I don't think your understanding is wrong, but I believe the better understanding would be that "contributors are consciously aware and agree that submitting code to this project means licensing the code under the project's license". Someone might argue in court that if they do not consciously aware and agree about it, things might be null.
> > I realize this issue in particular is a bit vaguely worded though. There isn't any clear actions suggested or anything like that.
> > But if you are someone who is concerned about potential issues, I do think it's better to take more steps to clear the copyright status. In things like copyright agreements or contracts in general, even the smallest wrong or vague details can make things a disaster.
> > More copyright-minding maintainers, like those that monetize their open source project, usually would make sure everything about the copyright is clear by having CLAs, DCOs, or license headers.
> > But generally as I write earlier taking these "extra" measures are not everywhere in the open source world. The convention in the Rust world is to include a copyright disclaimer in the README.
> 
> Thank you for your insight, i added a license disclaimer in [2537087](https://github.com/Lea-fish/Leafish/commit/2537087160fd88a18f4a2d7e6a448167243c1f5c) do you think this is sufficient?

I think it's sufficient if it's sufficiently able to make all contributors aware of the licensing. The "MIT and Apache 2.0 licenses found" text that GitHub sets in the repository meta should be visible to newcoming contributors. 

Another way you could do is by adding a GitHub Action that will comment on every new PRs, or pull request templates that includes a tick box that says "I license these contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option." It's not a common practice though.

**Comment by skillman623** [comment]
Fixed in https://github.com/Lea-fish/Leafish/commit/2537087160fd88a18f4a2d7e6a448167243c1f5c
