### ISSUE TITLE
Does not build ootb

### ISSUE THREAD

**Issue by iphands** [Lea-fish/Leafish#255]
Are we pointing at a commit that does not exist as a dep (in the lockfile)?
```
$ cargo build --release
    Updating git repository `https://github.com/terrarier2111/bevy`
error: failed to get `bevy_ecs` as a dependency of package `leafish v0.1.0 (/home/iphands/prog/Leafish)`

Caused by:
  failed to load source for dependency `bevy_ecs`

Caused by:
  Unable to update https://github.com/terrarier2111/bevy#a58b4936

Caused by:
  object not found - no match for id (a58b4936d0e1ccd241dca74bceae78a1b6d4f949); class=Odb (9); code=NotFound (-3)
  ```

**Comment by iphands** [comment]
If I depend on the rev specified in the lock file explicitly I can build...
`bevy_ecs = { git = "https://github.com/terrarier2111/bevy", rev = "a58b4936d0e1ccd241dca74bceae78a1b6d4f949" }`

**Comment by iphands** [comment]
```
diff --git a/Cargo.toml b/Cargo.toml
index cca075f..d2f7496 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -55,7 +55,7 @@ crossbeam-channel = "0.5.1" # check if flume would be better in terms of perform
 # tokio = { version = "0.2", features = ["full"] } # readd as soon as we want to impl this!
 rayon = "1.5.1"
 rfd = "0.5.0"
-bevy_ecs = { git = "https://github.com/terrarier2111/bevy" }
+bevy_ecs = { git = "https://github.com/terrarier2111/bevy", rev = "a58b4936d0e1ccd241dca74bceae78a1b6d4f949" }

 reqwest = { version = "0.11.4", features = [ "blocking" ]}
 glutin = "0.27.0"
diff --git a/protocol/Cargo.toml b/protocol/Cargo.toml
index 0d53724..6976b4f 100644
--- a/protocol/Cargo.toml
+++ b/protocol/Cargo.toml
@@ -24,7 +24,7 @@ trust-dns-resolver = "0.20.3"

 dashmap = "4.0.2"

-bevy_ecs = { git = "https://github.com/terrarier2111/bevy" }
+bevy_ecs = { git = "https://github.com/terrarier2111/bevy", rev = "a58b4936d0e1ccd241dca74bceae78a1b6d4f949" }

 reqwest = { version = "0.11.3", features = [ "blocking" ]}

diff --git a/shared/Cargo.toml b/shared/Cargo.toml
index ebd6c16..c371c4f 100644
--- a/shared/Cargo.toml
+++ b/shared/Cargo.toml
@@ -5,4 +5,4 @@ authors = [ "Thinkofdeath <thinkofdeath@spigotmc.org>" ]
 edition = "2018"

 [dependencies]
-bevy_ecs = { git = "https://github.com/terrarier2111/bevy" }
+bevy_ecs = { git = "https://github.com/terrarier2111/bevy", rev = "a58b4936d0e1ccd241dca74bceae78a1b6d4f949" }
```

**Comment by harkamalsr** [comment]
I had the same issue and was able to fix it by running `cargo update`. Just fyi for anyone who's having trouble with this right now

**Comment by harkamalsr** [comment]
Nevermind can't compile now, getting this error

https://pastebin.com/Rk7TUaV2

**Comment by harkamalsr** [comment]
Okay with the help of cooltexture on the discord we deduced that the issue was fixed upstream in stevenarella.
 
https://github.com/iceiix/stevenarella/commit/ba3cf43f932fec1c1d4c490e0269ee79cd74c80f

In the commit they were able to fix it by updating winit, glutin and changing the lines for the cursor grabbing code. After doing the same on the latest commit cooltexture and I were able to get everything running. Both the original object not found issue was fixed and also the wayland issue that cooltexture and I experienced

**Comment by nathanruiz** [comment]
@harkamalsr Thanks for reporting this bug! This seems like a different issue based on your description, although running `cargo update` might be the solution to both. The original problem is specifically related to our custom version of `bevy_ecs`. I'll take a look to see if I can get both working in the next few days.
