### ISSUE TITLE
Builds are failing due to bevy commit not being tracked

### ISSUE THREAD

**Issue by nathanruiz** [Lea-fish/Leafish#263]
One of the issues with the build at the moment is that there isn't any branch or tag pointing to the commit `a58b4936d0e1ccd241dca74bceae78a1b6d4f949` on the current bevy fork (https://github.com/terrarier2111/bevy). I've made a branch called `leafish` on my fork (https://github.com/nathanruiz/bevy) that points to that commit so we can easily move it across.

@terrarier2111 Would you be able to create that tag/branch?

**Comment by skillman623** [comment]
You can create a pull request for a specific branch. If you have fixed it in your personal repo, navigate to the bevy fork and create a PR while having the desired target branch selected.

**Comment by nathanruiz** [comment]
I was trying to avoid making a PR since the current main branch seems to be a single commit rebased onto bevy's main branch at a point in time.

It would be better for @terrarier2111 to tag this commit directly, so that it won't be lost again in case of another rebase.

**Comment by terrarier2111** [comment]
> 

Tbh normally i just revert the commit and redo it again as there are a lot of changes going on inside bevy any my change is only a one-liner

**Comment by nathanruiz** [comment]
@terrarier2111 Can you create that tag on your fork so that the builds will start working again? It doesn't matter what the tag is called, as long as it exists, it should be fine.

**Comment by terrarier2111** [comment]
We are now using the official latest release of bevy
