### ISSUE TITLE
fails to build on windows

### ISSUE THREAD

**Issue by strawbberrys** [Lea-fish/Leafish#284]
C:\Users\strawberrys\Downloads\Leafish>cargo build --release
    Updating git repository `https://github.com/terrarier2111/bevy`
error: failed to get `bevy_ecs` as a dependency of package `leafish v0.1.0 (C:\Users\strawberrys\Downloads\Leafish)`

Caused by:
  failed to load source for dependency `bevy_ecs`

Caused by:
  Unable to update https://github.com/terrarier2111/bevy?rev=a58b4936d0e1ccd241dca74bceae78a1b6d4f949#a58b4936

Caused by:
  object not found - no match for id (a58b4936d0e1ccd241dca74bceae78a1b6d4f949); class=Odb (9); code=NotFound (-3)

**Comment by nathanruiz** [comment]
@strawbberrys Would you be able to try that again with the current version?

**Comment by strawbberrys** [comment]
It now builds successfully, thanks
