### ISSUE TITLE
Fix post 1.13.2 textures

### ISSUE THREAD

**Issue by terrarier2111** [Lea-fish/Leafish#29]
The textures for post 1.13.2 blocks are buggy, we should fix them

**Comment by iceiix** [comment]
This may be relevant: https://github.com/iceiix/stevenarella/pull/71
If you only want to support post-flattening resource packs, easiest solution would be to update RESOURCES_VERSION, and the corresponding texture names

**Comment by PureTryOut** [comment]
Fixed by #191

**Comment by terrarier2111** [comment]
Sadly, this isn't fully fixed as the 1.13 don't load yet.

**Comment by nathanruiz** [comment]
Fixed by #256
