### ISSUE TITLE
Key binding issues

### ISSUE THREAD

**Issue by terrarier2111** [Lea-fish/Leafish#315]
After updating winit the keybindings on non-US keyboards are scuffed

**Comment by terrarier2111** [comment]
We just need to compare the whole Keys and not just KeyCodes as those are just for US keys board layouts and Keys are automatically mapped by winit.

**Comment by skillman623** [comment]
Would it make sense to have a setting for keycodes for text input (typing) and whole keys for controls and vice versa??
The default minecraft launcher does this which allows me to use Dvorak for typing and use the traditional WSAD for movement without having to switch back and forth using a standard US keyboard.

This may be a separate issue.

**Comment by terrarier2111** [comment]
> Would it make sense to have a setting for keycodes for text input (typing) and whole keys for controls and vice versa?? The default minecraft launcher does this which allows me to use Dvorak for typing and use the traditional WSAD for movement without having to switch back and forth using a standard US keyboard.
> 
> This may be a separate issue.

I am not exactly sure i understand what you mean i was just refering to Keys as the virtual keys (mapped by the os) abd KeyIds as the raw ids the hardware sends (and which is by default designed as a US keyboard)

**Comment by skillman623** [comment]
For KDE there are some issues with apps not respecting user set keyboard preferences.
Rereading what you posted, it doesn't seem like this would cause that issue.

**Comment by terrarier2111** [comment]
Fixed by https://github.com/Lea-fish/Leafish/pull/321
