### ISSUE TITLE
Wayland cursor locking buggy

### ISSUE THREAD

**Issue by terrarier2111** [Lea-fish/Leafish#316]
Cursor locking on wayland seems to be non-functional after the winit update

It doesn't work in-game (the cursor gets hidden but can escape from the window)
Weirdly enough upon leaving the server and getting back into the server list it seems to suddenly work

**Comment by skillman623** [comment]
For me I had it happen intermittently, within the same session connected to the server. It works most of the time and occasionally I would get a on hover description on the taskbar (the left hand side on Ubuntu), although clicking doesn't seem to escape the window.
