### ISSUE TITLE
Fix cursor visibility/cursor grab

### ISSUE THREAD

**Issue by terrarier2111** [Lea-fish/Leafish#36]
The cursor visibility/cursor grab are very buggy atm. we should improve them

**Comment by terrarier2111** [comment]
This is hard as it's most likely an bug in wayland or winit

**Comment by skillman623** [comment]
> This is hard as it's most likely an bug in wayland or winit (or another external lib)

The [relevant ticket](https://github.com/rust-windowing/winit/issues/591) in Winit.

**Comment by terrarier2111** [comment]
Fixed by https://github.com/Lea-fish/Leafish/pull/318
