### ISSUE TITLE
Non-premium accounts

### ISSUE THREAD

**Issue by Z2Up1UwcaYOyZq** [Lea-fish/Leafish#49]
because yes

**Comment by terrarier2111** [comment]
Is this related to https://github.com/terrarier2111/Leafish/issues/47?

**Comment by Z2Up1UwcaYOyZq** [comment]
No, #47 is about being able to play offline, while this one is about being able to join servers without premium account

**Comment by PureTryOut** [comment]
Without an account, meaning servers that have Mojang authentication turned off? Seems useful, but I would stay clear from the word "cracked" as that honestly makes it sound illegal. While if done correctly, there is nothing wrong with using no Mojang/Microsoft account to join alternative Minecraft implementations.

But I guess to implement this it would just need offline mode, but still be able to join servers? Thus not talking to Microsoft servers.

**Comment by Z2Up1UwcaYOyZq** [comment]
Client wouldn't even need offline mode, since server is hosted by someone else, right?

**Comment by PureTryOut** [comment]
I just see "offline mode" as in not authenticating with Microsoft servers. That doesn't mean you have to be restricted to single player.

**Comment by MavisCelus19201** [comment]
> I just see "offline mode" as in not authenticating with Microsoft servers. That doesn't mean you have to be restricted to single player.

I think that's basically how it is, I know hosted servers can disable that in config which allows for that, that's also why Beta servers exist since auth for those died years ago.

**Comment by waleed177** [comment]
Yes, because there are 'minecraft' servers that arent using the offical minecraft server (Cuberite). So atleast if both server and client have nothing to do with mojang or microsoft, then any authentication method is fine.

**Comment by fulcanelly** [comment]
So. is it so hard ?

**Comment by terrarier2111** [comment]
Closing this in order to comply with mojang's TOS
