### ISSUE TITLE
UI Scaling Issue in Main Menu

### ISSUE THREAD

**Issue by DeusFerrariis** [Lea-fish/Leafish#65]
# UI Scaling Issue in Main Menu

# Issue

The scaling for the UI in the main menu is disproportionate to the window size. The issue persists between fullscreen and windowed modes. This issue (seems) to not affect the asset download notifications in the bottom left corner. Compiled from commit  [de2d569462e91d561b77ae3c3f8a21b95cdd2d86](https://github.com/terrarier2111/Leafish/commit/de2d569462e91d561b77ae3c3f8a21b95cdd2d86).

## System Specs

- OS: Manjaro Linux x86_64
- CPU: Intel i7-856U
- GPU: Intel UHD Graphics 620
- Memory: 16GB
- WM: LeftWM
- Window System: X11
- Monitors (in order) 1920x1080, 1920x1080, 3840x2160

## Screenshot

![leafish_scaling_screenshot](https://user-images.githubusercontent.com/63998977/131747854-dbb67594-4cff-4c36-b902-735787bbe16f.png)

### Note

I'd like to work on this if there's no time for the current maintainers/contributors to work on this.

**Comment by terrarier2111** [comment]
This should be fixed by my newest commit, sorry that I did the work already

**Comment by Z2Up1UwcaYOyZq** [comment]
>I'd like to work on this if there's no time for the current maintainers/contributors to work on this.

Get in touch with developers by joining our matrix and discord channels. We need a lot of fetures to be implemented so feel free to pick one and commit to it, just give us a ping on which one tho, so we don't double.

**Comment by PureTryOut** [comment]
Assuming this fixed per @terrarier2111's comment.
