### ISSUE TITLE
Public server for testing Leafish?

### ISSUE THREAD

**Issue by Z2Up1UwcaYOyZq** [Lea-fish/Leafish#82]
Right now we don't need one, but maybe later, to test regressions/ bugs/ networking

**Comment by PureTryOut** [comment]
Someone is allowed to set one up of course, but I'm not sure why we should provide one. Also not sure how useful it is, Leafish needs to be tested over quite a lot of versions for compatibility, so one specific server won't do it.

Way easier to just run whatever you need locally while testing.

**Comment by PureTryOut** [comment]
Closing this, people should just set up their own servers.
